apiVersion: v1
kind: Service
metadata:
  name: quarterly-earnings-service
spec:
  selector:
    app.kubernetes.io/name: quarterly-earnings-tool
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376