apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarterly-earnings-deployment
  labels:
    app: quarterly-earnings-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: quarterly-earnings-app
  template:
    metadata:
      labels:
        app: quarterly-earnings-app
    spec:
      containers:
      - name: alpine
        image: alpine
        command:
        - sleep
        - "3600"
        ports:
        - containerPort: 1234  # this is the port our Pods will listen on
          name: our-svc-port   # the port can have a name
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarterly-earnings-data-processing-service-deployment
  labels:
    app: quarterly-earnings-data-processing-service
spec:
  replicas: 5
  selector:
    matchLabels:
      app: quarterly-earnings-data-processing-service
  template:
    metadata:
      labels:
        app: quarterly-earnings-data-processing-service
    spec:
      containers:
      - name: quarterly-earnings-data-processing-service
        image: quarterly-earnings-data-processing-service:1.25.4
        ports:
        - containerPort: 80
apiVersion: v1
kind: Namespace
metadata:
  name: quarterly-earnings
apiVersion: v1
kind: Pod
metadata:
  name: quarterly-earnings-pod-1
spec:
  terminationGracePeriodSeconds: 2
  containers:
  - name: alpine
    image: alpine
    command:
    - sleep
    - "3600"
    volumeMounts:
    - name: pv-mydata
      mountPath: /mydata
  volumes:
  - name: pv-mydata
    persistentVolumeClaim:
      claimName: quarterly-earnings-pvc
---
apiVersion: v1
kind: Pod
metadata:
  name: quarterly-earnings-pod-2
spec:
  terminationGracePeriodSeconds: 2
  containers:
  - name: alpine
    image: alpine
    command:
    - sleep
    - "3600"
    volumeMounts:
    - name: pv-mydata
      mountPath: /mydata
  volumes:
  - name: pv-mydata
    persistentVolumeClaim:
      claimName: quarterly-earnings-pvc
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: quarterly-earnings-statefulset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: quarterly-earnings-statefulset
  template:
    metadata:
      labels:
        app: quarterly-earnings-statefulset
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: alpine
        image: alpine:3.19.1
        command:
        - sleep
        - "3600"
apiVersion: v1
kind: Pod
metadata:
  name: outlier-detection-1
spec:
  terminationGracePeriodSeconds: 2
  restartPolicy: Never
  containers:
  - name: outlier-detection
    image: outlier-detection:v1
---
apiVersion: v1
kind: Pod
metadata:
  name: outlier-detection-2
spec:
  terminationGracePeriodSeconds: 2
  restartPolicy: Never
  containers:
  - name: outlier-detection
    image: outlier-detection:v2
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quarterly-earnings-pvc
spec:
  storageClassName: local-path
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10M
apiVersion: v1
kind: Service
metadata:
  name: quarterly-earnings-service
spec:
  selector:
    app: quarterly-earnings-app
  ports:
    - protocol: TCP             # this is merely the default protocol
      port: 9876                # this is the port for reaching the service
      targetPort: our-svc-port  # this is the named port declared in the deployment
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: quarterly-earnings-statefulset
  namespace: quarterly-earnings
spec:
  replicas: 6
  selector:
    matchLabels:
      app: quarterly-earnings-statefulset
  template:
    metadata:
      labels:
        app: quarterly-earnings-statefulset
    spec:
      terminationGracePeriodSeconds: 2
      containers:
      - name: alpine
        image: alpine
        command:
        - sleep
        - "3600"
        volumeMounts:
        - name: pv-mydata
          mountPath: /mydata
  volumeClaimTemplates:
  - metadata:
      name: pv-mydata
    spec:
      accessModes:
      - "ReadWriteOnce"
      storageClassName: local-path
      resources:
        requests:
          storage: 10MiapiVersion: apps/v1
kind: Deployment
metadata:
  name: quarterly-earnings-data-processing-service-deployment
  labels:
    app: quarterly-earnings-data-processing-service
spec:
  replicas: 5
  selector:
    matchLabels:
      app: quarterly-earnings-data-processing-service
  template:
    metadata:
      labels:
        app: quarterly-earnings-data-processing-service
    spec:
      containers:
      - name: quarterly-earnings-data-processing-service
        image: quarterly-earnings-data-processing-service:1.25.4
        ports:
        - containerPort: 80