apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
# data:
#   MYSQL_ROOT_PASSWORD: Y29udGFjdGZvcm0tcm9vdHBhc3M=     # base64 encoded
#   MYSQL_USER: Y29udGFjdGZvcm1kYi1hZG1pbg==              # base64 encoded
#   MYSQL_PASSWORD: Y29udGFjdGZvcm0tcGFzc3dvcmQ=          # base64 encoded
#   PMA_PASSWORD: Y29udGFjdGZvcm0tcGFzc3dvcmQ=
#   PMA_USER: Y29udGFjdGZvcm1kYi1wbWFkbWlu
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword | b64enc | quote }}
  MYSQL_USER: {{ .Values.mysql.user | b64enc | quote }}
  MYSQL_PASSWORD: {{ .Values.mysql.password | b64enc | quote }}
  PMA_PASSWORD: {{ .Values.pma.password | b64enc | quote }}
  PMA_USER: {{ .Values.pma.user | b64enc | quote }}