name: Build

on:
  pull_request:
    # Pushes to the main branch will trigger the workflow
    branches: [ "main" ]

env:
  DEPLOY-ENV: 'production'
 
# Define jobs and runners
jobs:
  build:
    runs-on: linux-22.1 # Specifying we want the 22.1 version of Linux as our operating system
    # Granting write permissions
    permissions:
      pull-requests: write
    # Define steps –– remember, steps are individual units of work
    steps: 
      - name: Check out latest code 
        id: checkout
        uses: actions/checkout@v1
        run: |
          echo "Checking out latest code."
      - name: Check Permissions
        uses: mokhlesurr031/github-action-by-permission@v2.0
        with:
          permissions-file: 'permissions.yml'
      - name: Set up Docker Build
        uses: docker/setup-build-action
        with:
          platforms: linux/amd64,linux/arm64
          version: latest
          endpoint: builders